# Generated by Django 5.1.4 on 2026-05-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('language', models.CharField(default='fr', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('crops', models.JSONField(default=list)),
                ('surface', models.FloatField(default=1.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('agri_score', models.IntegerField(default=70)),
                ('total_revenue', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('saved_vs_intermediaries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Durée en mois')),
                ('purpose', models.CharField(max_length=200)),
                ('purpose_emoji', models.CharField(default='🌱', max_length=10)),
                ('imf_name', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=8.0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'En cours'), ('repaid', 'Remboursé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='agrilink.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('crop_emoji', models.CharField(default='🌾', max_length=10)),
                ('surface', models.FloatField()),
                ('season', models.CharField(max_length=50)),
                ('premium', models.IntegerField()),
                ('coverage', models.IntegerField()),
                ('risk_index', models.IntegerField(default=30)),
                ('rainfall_30d', models.FloatField(default=45)),
                ('imf', models.CharField(default='AXA Assurances Sénégal', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='agrilink.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🌾', max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('quality', models.CharField(choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Standard', 'Standard')], default='Grade A', max_length=20)),
                ('price_per_kg', models.IntegerField()),
                ('market_price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(max_length=100)),
                ('available', models.DateField()),
                ('photo_url', models.URLField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='agrilink.farmer')),
            ],
        ),
    ]
